application: ghilbert2
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static
  
- url: /tree/.*
  script: tree.py

- url: /.*
  script: ghapp.py

