application: helloworld
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /peano
  static_dir: peano

- url: /.*
  script: ghapp.py
